# Generated by Django 3.2.5 on 2021-08-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaunica',
            name='texto',
            field=models.CharField(max_length=500),
        ),
    ]
