# Generated by Django 3.2.5 on 2021-08-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0002_alter_preguntaunica_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaMulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='esta respuetas correcta')),
                ('textos', models.CharField(max_length=20, verbose_name='texto de la respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta', to='pregunta.preguntaunica')),
            ],
        ),
    ]
