# Generated by Django 3.2.5 on 2021-08-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0005_cargarp_preguntasopcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('texto', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='preguntasopcion',
            name='preguntas',
        ),
        migrations.DeleteModel(
            name='CargarP',
        ),
        migrations.DeleteModel(
            name='pais',
        ),
        migrations.DeleteModel(
            name='PreguntasOpcion',
        ),
    ]
