# Generated by Django 3.2.5 on 2021-08-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0007_preguntasopcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreguntasBlog',
        ),
    ]
