# Generated by Django 3.2.5 on 2021-08-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0008_delete_preguntasblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('texto', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='PreguntasOpcion',
        ),
    ]
