# Generated by Django 3.2.5 on 2021-08-03 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.CharField(max_length=2)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('profeccion', models.CharField(max_length=40)),
                ('actual', models.IntegerField(choices=[[0, 'Si'], [1, 'No']])),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='formulario.cargo')),
            ],
        ),
    ]
