# Generated by Django 3.2.5 on 2021-08-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_rename_actual_formulario_trabaja_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='texto',
            field=models.TextField(verbose_name='pregunta'),
        ),
    ]
