# Generated by Django 3.2.5 on 2021-08-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_alter_cargo_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='texto',
            field=models.TextField(verbose_name='cargo'),
        ),
    ]
