# Generated by Django 3.2.5 on 2021-08-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20210824_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficluty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(default=2, help_text='required score in % '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=3, help_text='duration of the quiz in minute'),
            preserve_default=False,
        ),
    ]
