# Generated by Django 3.2.5 on 2021-08-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_auto_20210824_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficluty',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='required_score_to_pass',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
    ]
